version: "3.3"

services:

  jenkins:
    image: sgvv/sampleGetTest/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
